version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"  # Fixed port for Web UI

  store-data:
    image: quay.io/minio/mc
    container_name: client
    depends_on:
      - minio
    volumes:
      - .:/data
    environment:
      - MC_HOST_MYSTORAGE=http://minioadmin:minioadmin@minio:9000
    stdin_open: true  # Keep container interactive
    tty: true         # Allocate a TTY
    entrypoint: >
      /bin/sh -c "
      mc mb MYSTORAGE/test;
      mc cp ./data/README.md MYSTORAGE/test;
      exec /bin/sh;  # Keep container open
      "
