name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-pnpm:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node environment (for building)
        uses: actions/setup-node@v4
        with:
          node-version: 22.15
          cache: "pnpm"

      - name: Fetch dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build project
        run: |
          pnpm build
